# Generated by Django 4.2.2 on 2023-06-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentacar',
            name='dias_agendados',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
